name: Draw keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.json"
      - "boards/**/*-layouts.dtsi"
      - "keymap_drawer.config.yaml"
      - ".github/workflows/draw.yml"

permissions:
  contents: write

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      commit_message: "Draw keymap (automated)"
